### ISSUE TITLE
Failing to write the new checksum to the checksum byte array

### ISSUE THREAD

**Issue by aleitner** [sohan/Diablo-2-Hero-Editor-Hacks#2]
I am trying to reset my stats, but when trying to generate the new checksum the process fails.

```
Diablo-2-Hero-Editor-Hacks [master] % python d2hax.py --reset-stats --file "/Applications/Diablo II/Save/guy.d2s"
copied /Applications/Diablo II/Save/guy.d2s to /Applications/Diablo II/Save/guy.d2s.20190903_022134
Traceback (most recent call last):
  File "d2hax.py", line 175, in <module>
    args.should_reset_arreat
  File "d2hax.py", line 131, in main
    write_d2s(data, save_file)
  File "d2hax.py", line 101, in write_d2s
    byte_array[CHECKSUM_POS:CHECKSUM_POS + CHECKSUM_SIZE] = list(struct.pack('<i', checksum))
ValueError: invalid literal for long() with base 10: '\x86'
```

**Comment by sohan** [comment]
Ah thanks for the report and for trying out the script. I unfortunately haven't seen that error yet. Would you feel comfortable uploading your guy.d2s save file here so I can try to repro and debug?

**Comment by aleitner** [comment]
That's not a problem. This error occurs on all of my d2 save files at the moment.
[characters.zip](https://github.com/sohan/Diablo-2-Hero-Editor-Hacks/files/3567603/characters.zip)

**Comment by sohan** [comment]
Thanks! Curiously, I successfully reset the stats for `Barbstetty.d2s`

```
(diablo2) sohan@~/workspace/Diablo-2-Hero-Editor-Hacks (master) $ python d2hax.py --reset-stats --file /Applications/Diablo\ II/Save/Barbstetty.d2s
copied /Applications/Diablo II/Save/Barbstetty.d2s to /Applications/Diablo II/Save/Barbstetty.d2s.20190903_035015
wrote new file to /Applications/Diablo II/Save/Barbstetty.d2s
```

![image](https://user-images.githubusercontent.com/911977/64143093-76fb2c80-cdc3-11e9-8b18-67962c8bdac3.png)

So I'm thinking the issue must be caused by some difference between our environments. Couple of questions to further debug:

* Are you playing classic or LoD? (I'm on LoD)
* What patch are you using? (I'm on 1.14D)
* What version of python are you using? (I just tried it on 3.6.5)
* What OS + version are you running? (I'm on Mac OS 10.14.5. I haven't tried it on windows before but I believe others have successfully.)

**Comment by aleitner** [comment]
* LoD
* 1.14d
* 2.7
* 10.13.6

I just switched to use python 3.7.4 and the script worked no problem. Looks like an difference with python 2 libraries was causing the problem. Thanks!

**Comment by gaeduron** [comment]
Hello @sohan, I had the same issue as aleitner and I found a workaround.
My error was:
```
Traceback (most recent call last):
  File "d2hacks.py", line 181, in <module>
    args.should_reset_arreat
  File "d2hacks.py", line 137, in main
    write_d2s(data, save_file)
  File "d2hacks.py", line 107, in write_d2s
    byte_array[CHECKSUM_POS:CHECKSUM_POS + CHECKSUM_SIZE] = list(struct.pack('<i', checksum))
ValueError: invalid literal for long() with base 10: '\x87'
```

And I changed the function that way:✅
```python
def write_d2s(byte_array, out_fname='sohax.d2s'):
  byte_array = np.copy(byte_array)
  checksum = calculate_checksum(byte_array)
  checksum = list(struct.pack('<i', checksum))
  checksum = np.array([ord(checksum[0]),ord(checksum[1]),ord(checksum[2]),ord(checksum[3])])
  byte_array[CHECKSUM_POS:CHECKSUM_POS + CHECKSUM_SIZE] = checksum
  byte_array.tofile(out_fname)
  print('wrote new file to {}'.format(out_fname))
```

I hope that will help someone in the future.
And thank you @sohan for your cool script 😉
